project:
  type: website
  output-dir: docs


website:
  title: "Henry Gliedman Personal Webpage"
  navbar:
    left:
      - file: index.qmd
        text: "Home"
      - file: maps.qmd
        text: "Maps"
      - file: miniproject2.qmd
        text: "Mini Project_2"

      - file: Mini_Project_3.qmd
        text: "Mini Project 3"
page-footer:
    left: |
      &copy; Henry Gliedman, 2024<br>
      All content licensed under <i class='bi-badge-cc'></i>
      [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
    right: |
      Site built with <a href='https://quarto.org/'>Quarto</a>

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

